name: COOL Staging Plan
on:
  pull_request:
    branches: [develop]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.COOL_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.COOL_AWS_SECRET_ACCESS_KEY }}
  STAGING_ACCOUNT_ID: ${{ secrets.COOL_AWS_STAGING_ACCOUNT_ID }}
  REGION: us-east-1
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1

jobs:
  setenv:
    runs-on: ubuntu-latest
    outputs:
      ACCOUNT_ID: ${{ steps.env.outputs.ACCOUNT_ID }}
      ENVIRONMENT: ${{ steps.env.outputs.ENVIRONMENT }}
      ASSUME_ROLE: ${{ steps.env.outputs.ASSUME_ROLE }}
      ECR_URI: ${{ steps.env.outputs.ECR_URI }}
    steps:
      - uses: actions/checkout@v2
      - name: Echo Metadata
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}
      - name: Set Staging
        working-directory: ./cool/
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "ACCOUNT_ID=$STAGING_ACCOUNT_ID" >> $GITHUB_ENV
      - name: Set Environment
        run: |
          echo ::set-output name=ACCOUNT_ID::$(echo "$ACCOUNT_ID")
          echo ::set-output name=ENVIRONMENT::$(echo "$ENVIRONMENT")
          echo ::set-output name=ASSUME_ROLE::$(echo "arn:aws:iam::$ACCOUNT_ID:role/ProvisionAccount")
          echo ::set-output name=ECR_URI::$(echo "$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com")
        id: env

  tag_ui:
    runs-on: ubuntu-latest
    needs: [setenv]
    env:
      ENVIRONMENT: ${{ needs.setenv.outputs.ENVIRONMENT }}
      ASSUME_ROLE: ${{ needs.setenv.outputs.ASSUME_ROLE }}
      ECR_URI: ${{ needs.setenv.outputs.ECR_URI }}
      IMAGE_REPO: domain-manager-ui
    outputs:
      tag: ${{ steps.vars.outputs.tag}}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: cisagov/domain-manager-ui
      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::$(git rev-parse --short HEAD)

  tag_api:
    runs-on: ubuntu-latest
    needs: [setenv]
    env:
      ENVIRONMENT: ${{ needs.setenv.outputs.ENVIRONMENT }}
      ASSUME_ROLE: ${{ needs.setenv.outputs.ASSUME_ROLE }}
      ECR_URI: ${{ needs.setenv.outputs.ECR_URI }}
      IMAGE_REPO: domain-manager-api
    outputs:
      tag: ${{ steps.vars.outputs.tag}}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: cisagov/domain-manager-api
      - name: Get Tag
        id: vars
        run: echo ::set-output name=tag::$(git rev-parse --short HEAD)

  terraform:
    runs-on: ubuntu-latest
    needs: [tag_ui, tag_api, setenv]
    env:
      ACCOUNT_ID: ${{ needs.setenv.outputs.ACCOUNT_ID }}
      ENVIRONMENT: ${{ needs.setenv.outputs.ENVIRONMENT }}
    steps:

      # Checkout domain-manager repo for running terraform
      - uses: actions/checkout@v2
        with:
          path: domain-manager

      # Install Terraform
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.30
      - name: Verify Terraform version
        run: terraform --version

      # Initialize Terraform
      - name: Terraform init
        working-directory: ./domain-manager/cool
        run: terraform init -input=false

      # Select terraform workspace
      - name: Terraform Workspace
        working-directory: ./domain-manager/cool
        run: |
          terraform workspace select $ENVIRONMENT
          terraform workspace show

      # Validate Terraform
      - name: Terraform validation
        working-directory: ./domain-manager/cool
        run: terraform validate

      # Sometimes this just needs run again...
      - name: Terraform init 2
        working-directory: ./domain-manager/cool
        run: terraform init -input=false

      # Apply terraform
      - name: Terraform Plan
        working-directory: ./domain-manager/cool
        run: |
          terraform plan \
            -input=false \
            -var-file ./vars/$ENVIRONMENT.tfvars \
            -var="api_image_tag=${{needs.tag_api.outputs.tag}}" \
            -var="ui_image_tag=${{needs.tag_ui.outputs.tag}}" \
            -var="account_id=$ACCOUNT_ID"
