# name: COOL Staging Plan
# on:
#   pull_request:
#     branches: [develop]

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.COOL_AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.COOL_AWS_SECRET_ACCESS_KEY }}
#   STAGING_ACCOUNT_ID: ${{ secrets.COOL_AWS_STAGING_ACCOUNT_ID }}
#   SHARED_SERVICES_STAGING_ACCOUNT_ID: ${{ secrets.COOL_SHARED_SERVICES_STAGING_ACCOUNT_ID }}
#   REGION: us-east-1
#   AWS_REGION: us-east-1
#   AWS_DEFAULT_REGION: us-east-1

# jobs:
#   terraform:
#     runs-on: ubuntu-latest
#     steps:
#       # Install Terraform
#       - uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 0.12.30

#       # Verify Terraform version
#       - name: Verify Terraform version
#         run: terraform --version

#       # Checkout cicd repo
#       - uses: actions/checkout@v2
#         with:
#           path: cicd

#       # Checkout UI repo
#       - uses: actions/checkout@v2
#         with:
#           path: ui
#           repository: cisagov/domain-manager-ui

#       # Checkout API repo
#       - uses: actions/checkout@v2
#         with:
#           path: api
#           repository: cisagov/domain-manager-api

#       # Set environment variables
#       - name: Set Environment
#         run: |
#           echo "ACCOUNT_ID=$STAGING_ACCOUNT_ID" >> $GITHUB_ENV
#           echo "ENVIRONMENT=staging" >> $GITHUB_ENV
#           echo "SHARED_SERVICES_ACCOUNT_ID=$SHARED_SERVICES_STAGING_ACCOUNT_ID" >> $GITHUB_ENV
#         id: env

#       # Get UI tag
#       - name: Get UI Tag
#         id: ui_tag
#         run: echo "UI_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
#         working-directory: ./ui/

#       # Get API tag
#       - name: Get API Tag
#         id: api_tag
#         run: echo "API_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
#         working-directory: ./api/

#       # Initialize Terraform
#       - name: Terraform init
#         working-directory: ./cicd/cool
#         run: terraform init -input=false
      
#       # Select terraform workspace
#       - name: Terraform Workspace
#         working-directory: ./cicd/cool
#         run: |
#           terraform workspace select $ENVIRONMENT
#           terraform workspace show

#       # Validate Terraform
#       - name: Terraform validation
#         working-directory: ./cicd/cool
#         run: terraform validate

#       # Sometimes this just needs run again...
#       - name: Terraform init 2
#         working-directory: ./cicd/cool
#         run: terraform init -input=false

#       # Plan terraform
#       - name: Terraform Plan
#         working-directory: ./cicd/cool
#         run: |
#           terraform plan \
#             -input=false \
#             -var-file ./vars/$ENVIRONMENT.tfvars \
#             -var="api_image_tag=$API_TAG" \
#             -var="ui_image_tag=$UI_TAG" \
#             -var="account_id=$ACCOUNT_ID" \
#             -var="shared_services_account_id=$SHARED_SERVICES_ACCOUNT_ID"
