name: COOL Deploy
on:
  pull_request:
    branches: [develop]

env:
  BUILD_ENV: staging

jobs:
  test_staging:
    runs-on: ubuntu-latest
    environment: ${{ env.BUILD_ENV }}
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
    steps:
      # Output metadata
      - name: Test
        run: echo "$ACCOUNT_ID_test"
