name: COOL Deploy
on:
  pull_request:
    branches: [develop]

env:
  BUILD_ENV: staging

jobs:
  setenv:
    runs-on: ubuntu-latest
    outputs: 
      ENVIRONMENT: ${{ steps.env.outputs.ENVIRONMENT }}
    steps:
      - name: Set Environment
        id: env
        run: |
          echo "staging"
          echo ::set-output name=ENVIRONMENT::$(echo "staging")
  test_staging:
    runs-on: ubuntu-latest
    needs: [ setenv ]
    environment: 
      name: ${{ needs.setenv.outputs.ENVIRONMENT }}
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
    steps:
      - name: Test
        run: echo "$ACCOUNT_ID_test"
